BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    Button:
        id: reset_inputs
        text: 'Clear'
        on_press: app.handle_reset()
        # Note: make a new def to handle each individually
    TextInput:
        id: input_name
        text: ''
    Button:
        id: output_label
        text: 'Greet'
        on_press: app.handle_greet()
    Label:
        text: 'Enter your name'
        color: (1, 1, 0, 1)